---

- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy

- name: Upload haproxy configuration
  ansible.builtin.template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
      
- name: haproxy is started
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started
 

