---
   
- name: restart prometheus-bind-exporter
  ansible.builtin.service:
    name: prometheus-bind-exporter
    state: restarted
    
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
