{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "SQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy_UP",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "Agama Containers Al-x22-1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"Al-x22-1:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "Agama Containers Al-x22-2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"Al-x22-2:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{cpu=\"0\", mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(bind_resolver_queries_total [1m]))",
     "legendFormat": "auto"
    }
   ]
  },
  {
   "title": "SQL Selects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mysql_global_status_commands_total [1m]))"
    }
   ]
  },
  {
   "title": "InfluxDB Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(nginx_http_requests_total [1m]))"
    }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "Cloudflare",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "cloudflare.com" }
     ]
    },
    {
     "alias": "Google",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "Twitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dst", "operator": "=", "value": "twitter.com" }
     ]
    }
   ]
  }
 ]
}