---

- name: Agama Doker directory /opt/agama
  ansible.builtin.file:
    name: /opt/agama
    state: directory
        
- name: Install agama.py and agama raw image in docker /opt dir
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}"
    dest: /opt/agama/
  loop:
    - agama.py
    - Dockerfile
    
- name: Build agama image
  community.docker.docker_image:
    name: agama
    build:
      path: /opt/agama
    source: build
    
- name: Add Agama to Docker provisioning
  community.docker.docker_container:
    name: agama
    image: agama
    published_ports: "{{ agama_port }}:8000"
    volumes: /opt/agama:/etc/agama
    env: AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
