---

- name: Add the user 'backup' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: backup
    comment: backup
    create_home: true
    group: admin
    home: /home/backup
    
- name: Create a 2048-bit SSH key for user backup
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    
- name: Template a file to /home/backup/.ssh/known_hosts
  ansible.builtin.template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    
   
