---

- name: Ensure path to cron influxdb-backup exists
  ansible.builtin.file:
    path: /etc/cron.d/influxdb-backup
    owner: root
    group: root
    mode: '0644'
    state: touch
 
- name: Upload cron influxdb-backup
  ansible.builtin.template:
    src: influxdb-backup
    dest: /etc/cron.d/influxdb-backup
  no_log: yes
