---
- name: Add mysql to server
  ansible.builtin.apt:
    name: mysql-server

- name: Copy file override.cnf
  ansible.builtin.copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql
  
- name: Ensure sql is always started please
  ansible.builtin.service:
    name: mysql
    enabled: yes
    state: started
    
- name: Add python3-pymysql because it is required
  ansible.builtin.apt:
    name: python3-pymysql
    
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: MySQL user for Exporter
  community.mysql.mysql_user:
    name: "{{ sql_exporter_user }}"
    password: "{{ sql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
    
