---

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    
- name: restart nginx&exporter
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nginx
    - prometheus-nginx-exporter
