---

- name: restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted
    
- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
