---

- name: Download keepalived exporter
  ansible.builtin.get_url:
    url: https://github.com/cafebazaar/keepalived-exporter/releases/download/v{{ka_version}}/keepalived-exporter-{{ka_version}}.linux-amd64.tar.gz
    dest: /usr/local/bin/
    mode: '0666'
 
- name: Extract Keepalived exporter from tar.gz file
  ansible.builtin.unarchive:
    src: /usr/local/bin/keepalived-exporter-{{ka_version}}.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
       
- name: Add keepalived exporter Service
  ansible.builtin.template:
    dest: /etc/systemd/system/keepalived-exporter.service
    src: keepalived-exporter.service
  notify: restart keepalived exporter service

- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start keepalived uncodnitionally
  ansible.builtin.service:
    name: keepalived-exporter
    state: started
    enabled: yes
