---

- name: Install nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Ensure nginx exporter is always started please
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    enabled: yes
    state: started
    
- name: Upload prometheus-nginx-exporter configuration
  ansible.builtin.template:
    src: prometheus-nginx-exporter 
    dest: /etc/default/prometheus-nginx-exporter 
  notify: restart prometheus-nginx-exporter 
  no_log: yes
    
    
   
