---

- name: Install Bind9
  ansible.builtin.apt:
    name: bind9
    
- name: Bind is started
  ansible.builtin.service:
    name: bind9
    enabled: yes
    state: started
 
- name: Upload bind9 configuration
  ansible.builtin.template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  notify: restart bind9
  no_log: yes
  
- name: Upload bind9 local configuration
  ansible.builtin.template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  notify: restart bind9
  no_log: yes
  
- name: Upload bind9 local db configuration
  ansible.builtin.template:
    src: db.alba.pz.j2
    dest: /var/cache/bind/db.{{ startup_name }}.j2
    force: false
  notify: Restart dns zone
  when: inventory_hostname in groups['dns_masters']
  no_log: yes
  
- name: Upload bind9 rev db configuration
  ansible.builtin.template:
    src: db.rev.j2
    dest: /var/cache/bind/db.rev
    force: true
  notify: Restart dns zone
  when: inventory_hostname in groups['dns_masters']
  no_log: yes

    
